;Вікно налаштувань
Settings.title:Налаштування
Settings.cmdOpenFolder:Відкрити
Settings.collectionFolder:Папка
Settings.collectionFileName:Файл
Settings.cmdChangePath:Змінити
Settings.collectionType:Колекція задач
Settings.collectionTypeFolder:Папка з файлами
Settings.collectionTypeSingleFile:Один файл

;
LoadingForm.title:Завантажується колекція...
LoadingForm.emptyCollection:Колекція порожня
LoadingForm.collectionError:Помилка колекції
LoadingForm.problemsFound:Знайдено: 
